name: Prepare Environments

on:
  workflow_call:
    inputs:
      group:
        required: true
        type: string
    outputs:
      envs: 
        description: JSON Array of the environment sequence for the group
        value: ${{ jobs.prepare_envs.outputs.envs }}
      
jobs:
  prepare_envs:
    name: "Prepare ${{ inputs.group }} Environments"
    runs-on: ubuntu-latest
    
    outputs:
      envs: ${{ steps.set-matrix.outputs.envs }}

    steps:
      - id: set-matrix
        shell: bash
        run: |
          envs=$(cat <<-EOJSON
            {
              "":   ["dev", "test", "prod"]
              "ea": ["eadev", "eatest", "eaprod"]
            }
            EOJSON
          )

          envjson="$(jq -e --arg env '${{ inputs.group }}' '.[$env]?' <<< "$envs")"
          if [[ $? -eq 1 ]]; then
            echo "::Error::Unknown environment group."
            exit 1
          fi

          echo "Environments for group: $envjson"
          echo "envs=$envjson" >> "$GITHUB_OUTPUT"
