name: Deploy App Service Workflow

on:
  workflow_call:
    inputs:
      environment-group:
        type: string
        description: The name of the environment group to deploy to.
        required: false
        default: ""

jobs:
  prepare:
    uses: ./.github/workflows/__environments.yml
    name: "Prepare ${{ inputs.environment-group }} Environments"
    with:
      group: ${{ inputs.environment-group }}

  deploy:
    needs: prepare
    strategy:
      matrix:
        environment: ${{ fromJSON(needs.prepare.outputs.envs) }}

    name: "Deploy ${{ matrix.environment }}"
    environment: ${{ matrix.environment }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Deploy ${{ matrix.environment }}'
