name: Master

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_dotnet:
    name: "Build .NET App"
    runs-on: ubuntu-latest
    steps:
      - name: Build the app
        run: echo "Build etc."

  publish_acr:
    name: "Publish to Container Registry"
    runs-on: ubuntu-latest
    steps:
      - name: Publish to ACR
        run: echo "Publish here"

  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      group: ""

