name: Prepare Environments

on:
  workflow_call:
    inputs:
      group:
        required: true
        type: string
      
jobs:
  prepare_envs:
    name: "Prepare ${{ inputs.group }} Environments"
    runs-on: ubuntu-latest
    outputs:
      envs: ${{ steps.set-matrix.outputs.envs }}
    steps:
      - id: set-matrix
        shell: bash
        run: |
          case "${{ input.group }}" in
            "")
              envs=(dev test prod)
            "ea")
              envs=(eadev eatest eaprod)
          esac

          envjson=jq -nc '{environment: $ARGS.positional}' --args ${envs[@]}
          echo "envs=$envjson" >> $GITHUB_OUTPUT
